# yum and service modules with sudo access

---
- hosts: localhost
  become: yes
  tasks:

# This task will install apache http server
  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Install httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

# This task will start apache http server
  - name: Start httpd
    service:
      name: httpd 
      state: started 
      enabled: yes
    when: ansible_os_family == "RedHat"

  - name: Start apache2
    service:
      name: apache2
      state: started 
      enabled: yes
    when: ansible_os_family == "Debian"
